import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local"

const inter = Inter({ subsets: ["latin"] });
const font = localfont({
  src:'./static-fonts/NeuzeitGro-Bla.ttf',
  variable:"--font-neu",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`$font.variable`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
